version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/DockerFile.server
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/
    command: /bin/bash -c "uvicorn main:app --reload --host "0.0.0.0""
